version: '3.2'

services:
  extractor-debug:
    build:
      context: text-extract-model-service
      dockerfile: debug.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./text-extract-model-service:/app
    networks:
      - net
    profiles:
      - debug
  
  generator-debug:
    build:
      context: quiz-generator-service
      dockerfile: debug.Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./quiz-generator-service:/app
    env_file:
    - .env
    networks:
      - net
    profiles:
      - debug
  
  backend-debug:
    image: lang-learn-quiz-bot-backend:latest
    ports:
      - "8080:8080"
    networks:
      - net
    profiles:
      - debug
    environment:
      SPRING_PROFILES_ACTIVE: debug
    depends_on:
      generator-debug:
        condition: service_started      
      extractor-debug:
        condition: service_started
      redis:
        condition: service_started

  frontend-debug:
    image: lang-learn-quiz-bot-frontend:latest
    env_file:
    - .env
    networks:
      - net
    profiles:
      - debug
    environment:
      SPRING_PROFILES_ACTIVE: debug
      TG_BOT_API: ${TG_BOT_API}
    depends_on:
      backend-debug:
        condition: service_started



  generator-test:
    build:
      context: quiz-generator-service
      dockerfile: test.Dockerfile
    volumes:
      - ./quiz-generator-service:/app
    env_file:
      - .env
    profiles:
      - test
    
  redis:
    image: redis:7.2.1
    ports:
      - "6379:6379"
    networks:
      - net

networks:
  net:
    driver: bridge
