version: '3.2'

services:
  extractor-debug:
    build:
      context: text-extract-model-service
      dockerfile: debug.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./text-extract-model-service:/app
    profiles:
      - debug
  
  generator-debug:
    build:
      context: quiz-generator-service
      dockerfile: debug.Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./quiz-generator-service:/app
    env_file:
    - .env
    profiles:
      - debug
  
  generator-test:
    build:
      context: quiz-generator-service
      dockerfile: test.Dockerfile
    volumes:
      - ./quiz-generator-service:/app
    env_file:
    - .env
    profiles:
      - test
