version: '3.2'

services:
  extractor-debug:
    build:
      context: text-extract-model-service
      dockerfile: debug.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./text-extract-model-service:/app
    networks:
      - net
    profiles:
      - debug
  
  generator-debug:
    build:
      context: quiz-generator-service
      dockerfile: debug.Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./quiz-generator-service:/app
    env_file:
    - .env
    networks:
      - net
    profiles:
      - debug
  
  backend-debug:
    build:
      context: backend
      dockerfile: debug.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net
    profiles:
      - debug
    depends_on:
      generator-debug:
        condition: service_started      
      extractor-debug:
        condition: service_started
      redis:
        condition: service_started
  
  
  generator-test:
    build:
      context: quiz-generator-service
      dockerfile: test.Dockerfile
    volumes:
      - ./quiz-generator-service:/app
    env_file:
    - .env
    profiles:
      - test

  frontend-debug:
    build:
      context: frontend
      dockerfile: debug.Dockerfile
    env_file:
    - .env
    networks:
      - net
    profiles:
      - debug
    depends_on:
      backend-debug:
        condition: service_started
    
  redis:
    image: redis:7.2.1
    ports:
      - "6379:6379"
    networks:
      - net

networks:
  net:
    driver: bridge
